const sampleItems = (() => {
  const make = (i, type = 'ANIME') => ({
    id: `${type.toLowerCase()}-${i}`,
    type,
    title: `${type === 'ANIME' ? 'Sample Anime' : 'Sample Manga'} ${i}`,
    coverUrl: `/images/sample-${(i % 6) + 1}.svg`,
    bannerUrl: `/images/sample-banner-${(i % 3) + 1}.svg`,
    description: 'This is a demo description generated by mock data.',
    rating: +(Math.random() * 4 + 6).toFixed(1),
    year: 2000 + (i % 22),
    episodeCount: type === 'ANIME' ? (12 + (i % 24)) : undefined,
    chapterCount: type === 'MANGA' ? (30 + (i % 120)) : undefined,
    status: ['ONGOING', 'COMPLETED', 'HIATUS'][i % 3],
    genres: ['Action', 'Adventure', 'Fantasy'].slice(0, (i % 3) + 1),
    inWatchlist: false,
    bookmarkCount: Math.floor(Math.random() * 5000),
    episodes: type === 'ANIME' ? Array.from({ length: 8 }).map((_, j) => ({
      id: `ep-${i}-${j+1}`,
      title: `Episode ${j+1}`,
      episodeNumber: j+1,
      seasonNumber: 1,
      thumbnailUrl: `/images/sample-${(i % 6) + 1}.svg`,
      duration: 1200 + j * 60
    })) : [],
  });

  const items = [];
  for (let i = 1; i <= 24; i++) {
    items.push(make(i, i % 2 === 0 ? 'ANIME' : 'MANGA'));
  }
  return items;
})();

const mockApi = {
  async getFeatured() {
    return { featured: sampleItems.slice(0, 6) };
  },

  async getContent(params = {}) {
    const {
      type,
      limit = 15,
      page = 1,
      search = '',
      genre,
      year,
      status,
      sort
    } = params;

    let list = sampleItems.slice();
    if (type) list = list.filter(i => i.type === type);
    if (genre) list = list.filter(i => (i.genres || []).map(g => g.toLowerCase()).includes(String(genre).toLowerCase()));
    if (year) list = list.filter(i => String(i.year) === String(year));
    if (status) list = list.filter(i => String(i.status).toLowerCase() === String(status).toLowerCase());

    if (search && search.trim()) {
      const q = String(search).toLowerCase();
      list = list.filter(i => (
        (i.title || '').toLowerCase().includes(q) ||
        (i.description || '').toLowerCase().includes(q) ||
        (i.genres || []).join(' ').toLowerCase().includes(q)
      ));
    }

    // simple sort
    if (sort === 'rating') {
      list.sort((a, b) => (b.rating || 0) - (a.rating || 0));
    } else if (sort === 'newest') {
      list.sort((a, b) => (b.year || 0) - (a.year || 0));
    }

    const total = list.length;
    const totalPages = Math.max(1, Math.ceil(total / limit));
    const currentPage = Math.max(1, Math.min(page, totalPages));
    const start = (currentPage - 1) * limit;
    const paged = list.slice(start, start + limit);

    return {
      content: paged,
      pagination: {
        total,
        page: currentPage,
        totalPages,
        limit
      }
    };
  },

  async getContentById(id) {
    const content = sampleItems.find(i => i.id === id) || null;
    return { content };
  },

  async getEpisodes(contentId) {
    const c = sampleItems.find(i => i.id === contentId);
    return { episodes: c ? c.episodes : [] };
  },

  async getChapters(contentId) {
    return { chapters: [] };
  },

  async getWatchlist() {
    return { watchlist: [] };
  },

  async getProgress() {
    return { progress: [] };
  },

  async getContentProgress(contentId) {
    return { progress: null };
  },

  async getRecommendations() {
    return { recommendations: sampleItems.slice(6, 14) };
  }
};

export default mockApi;
